# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _vine_graph_capi
else:
    import _vine_graph_capi

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import cvine
VINE_GRAPH_RUNNING = _vine_graph_capi.VINE_GRAPH_RUNNING
VINE_GRAPH_DONE = _vine_graph_capi.VINE_GRAPH_DONE
VINE_GRAPH_FAILED = _vine_graph_capi.VINE_GRAPH_FAILED
VINE_GRAPH_NODE_WAITING = _vine_graph_capi.VINE_GRAPH_NODE_WAITING
VINE_GRAPH_NODE_COMPLETED = _vine_graph_capi.VINE_GRAPH_NODE_COMPLETED
VINE_GRAPH_NODE_FAILED = _vine_graph_capi.VINE_GRAPH_NODE_FAILED

def vine_graph_executor_create(manager, library_name, function_name):
    return _vine_graph_capi.vine_graph_executor_create(manager, library_name, function_name)

def vine_graph_executor_delete(e):
    return _vine_graph_capi.vine_graph_executor_delete(e)

def vine_graph_executor_tune(e, name, value):
    return _vine_graph_capi.vine_graph_executor_tune(e, name, value)

def vine_graph_executor_check_setting(name, value):
    return _vine_graph_capi.vine_graph_executor_check_setting(name, value)

def vine_graph_executor_add_node(e):
    return _vine_graph_capi.vine_graph_executor_add_node(e)

def vine_graph_executor_declare_file(e, source_path, vault):
    return _vine_graph_capi.vine_graph_executor_declare_file(e, source_path, vault)

def vine_graph_executor_undeclare_file(e, file_id):
    return _vine_graph_capi.vine_graph_executor_undeclare_file(e, file_id)

def vine_graph_executor_add_output(e, node_id, task_path):
    return _vine_graph_capi.vine_graph_executor_add_output(e, node_id, task_path)

def vine_graph_executor_add_input(e, node_id, file_id, task_path):
    return _vine_graph_capi.vine_graph_executor_add_input(e, node_id, file_id, task_path)

def vine_graph_executor_submit_node(e, node_id):
    return _vine_graph_capi.vine_graph_executor_submit_node(e, node_id)

def vine_graph_executor_pin_file(e, file_id):
    return _vine_graph_capi.vine_graph_executor_pin_file(e, file_id)

def vine_graph_executor_unpin_file(e, file_id):
    return _vine_graph_capi.vine_graph_executor_unpin_file(e, file_id)

def vine_graph_executor_fetch_file(e, file_id):
    return _vine_graph_capi.vine_graph_executor_fetch_file(e, file_id)

def vine_graph_executor_get_local_path(e, file_id):
    return _vine_graph_capi.vine_graph_executor_get_local_path(e, file_id)

def vine_graph_executor_wait(e, timeout):
    return _vine_graph_capi.vine_graph_executor_wait(e, timeout)

def vine_graph_executor_wake(e):
    return _vine_graph_capi.vine_graph_executor_wake(e)

def vine_graph_executor_next_finished(e):
    return _vine_graph_capi.vine_graph_executor_next_finished(e)

def vine_graph_executor_next_released(e):
    return _vine_graph_capi.vine_graph_executor_next_released(e)

def vine_graph_executor_get_node_state(e, node_id):
    return _vine_graph_capi.vine_graph_executor_get_node_state(e, node_id)

def vine_graph_executor_get_failure_source(e, node_id):
    return _vine_graph_capi.vine_graph_executor_get_failure_source(e, node_id)

def vine_graph_executor_get_node_error(e, node_id):
    return _vine_graph_capi.vine_graph_executor_get_node_error(e, node_id)

def vine_graph_executor_get_error(e):
    return _vine_graph_capi.vine_graph_executor_get_error(e)

def vine_graph_executor_get_makespan_us(e):
    return _vine_graph_capi.vine_graph_executor_get_makespan_us(e)

def vine_graph_executor_get_completed_recovery_tasks(e):
    return _vine_graph_capi.vine_graph_executor_get_completed_recovery_tasks(e)

def vine_graph_executor_cancel_node(e, node_id):
    return _vine_graph_capi.vine_graph_executor_cancel_node(e, node_id)

