# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _vine_graph_capi
else:
    import _vine_graph_capi

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import cvine

def vine_graph_create(runtime_dir):
    return _vine_graph_capi.vine_graph_create(runtime_dir)

def vine_graph_add_node(g):
    return _vine_graph_capi.vine_graph_add_node(g)

def vine_graph_set_target(g, node_id):
    return _vine_graph_capi.vine_graph_set_target(g, node_id)

def vine_graph_add_dependency(g, parent_id, child_id):
    return _vine_graph_capi.vine_graph_add_dependency(g, parent_id, child_id)

def vine_graph_finalize(g):
    return _vine_graph_capi.vine_graph_finalize(g)

def vine_graph_get_node_outfile_remote_name(g, node_id):
    return _vine_graph_capi.vine_graph_get_node_outfile_remote_name(g, node_id)

def vine_graph_delete(g):
    return _vine_graph_capi.vine_graph_delete(g)

def vine_graph_get_task_runner_library_name(g):
    return _vine_graph_capi.vine_graph_get_task_runner_library_name(g)

def vine_graph_set_task_runner_function_name(g, task_runner_function_name):
    return _vine_graph_capi.vine_graph_set_task_runner_function_name(g, task_runner_function_name)

def vine_graph_tune(g, name, value):
    return _vine_graph_capi.vine_graph_tune(g, name, value)
TASK_PRIORITY_MODE_RANDOM = _vine_graph_capi.TASK_PRIORITY_MODE_RANDOM
TASK_PRIORITY_MODE_DEPTH_FIRST = _vine_graph_capi.TASK_PRIORITY_MODE_DEPTH_FIRST
TASK_PRIORITY_MODE_BREADTH_FIRST = _vine_graph_capi.TASK_PRIORITY_MODE_BREADTH_FIRST
TASK_PRIORITY_MODE_FIFO = _vine_graph_capi.TASK_PRIORITY_MODE_FIFO
TASK_PRIORITY_MODE_LIFO = _vine_graph_capi.TASK_PRIORITY_MODE_LIFO
TASK_PRIORITY_MODE_LARGEST_INPUT_FIRST = _vine_graph_capi.TASK_PRIORITY_MODE_LARGEST_INPUT_FIRST
TASK_PRIORITY_MODE_LARGEST_STORAGE_FOOTPRINT_FIRST = _vine_graph_capi.TASK_PRIORITY_MODE_LARGEST_STORAGE_FOOTPRINT_FIRST

def vine_graph_executor_create(manager, graph):
    return _vine_graph_capi.vine_graph_executor_create(manager, graph)

def vine_graph_executor_create_graph(manager):
    return _vine_graph_capi.vine_graph_executor_create_graph(manager)

def vine_graph_executor_delete(e):
    return _vine_graph_capi.vine_graph_executor_delete(e)

def vine_graph_executor_add_node(e):
    return _vine_graph_capi.vine_graph_executor_add_node(e)

def vine_graph_executor_finalize(e):
    return _vine_graph_capi.vine_graph_executor_finalize(e)

def vine_graph_executor_declare_input_file(e, file_id, source_path, export_input):
    return _vine_graph_capi.vine_graph_executor_declare_input_file(e, file_id, source_path, export_input)

def vine_graph_executor_add_task_output_file(e, task_id, file_id, task_path, is_target):
    return _vine_graph_capi.vine_graph_executor_add_task_output_file(e, task_id, file_id, task_path, is_target)

def vine_graph_executor_add_task_input_file(e, task_id, file_id, task_path):
    return _vine_graph_capi.vine_graph_executor_add_task_input_file(e, task_id, file_id, task_path)

def vine_graph_executor_get_file_target_path(e, file_id):
    return _vine_graph_capi.vine_graph_executor_get_file_target_path(e, file_id)

def vine_graph_executor_tune(e, name, value):
    return _vine_graph_capi.vine_graph_executor_tune(e, name, value)

def vine_graph_executor_execute(e):
    return _vine_graph_capi.vine_graph_executor_execute(e)

def vine_graph_executor_get_makespan_us(e):
    return _vine_graph_capi.vine_graph_executor_get_makespan_us(e)

def vine_graph_executor_get_total_recovery_tasks(e):
    return _vine_graph_capi.vine_graph_executor_get_total_recovery_tasks(e)

def vine_graph_executor_get_completed_recovery_tasks(e):
    return _vine_graph_capi.vine_graph_executor_get_completed_recovery_tasks(e)

