#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
TASKS=${DATAVINE_GRAND_TASKS:-100}
MEDIUM_BYTES=${DATAVINE_GRAND_MEDIUM_BYTES:-65536}
LARGE_BYTES=${DATAVINE_GRAND_LARGE_BYTES:-0}
WORKERS=${DATAVINE_GRAND_WORKERS:-2}
WORKER_CORES=${DATAVINE_GRAND_WORKER_CORES:-2}
WORKFLOW_TIMEOUT=${DATAVINE_GRAND_WORKFLOW_TIMEOUT:-600}
WORKER_LOSS_COUNT=${DATAVINE_GRAND_WORKER_LOSS_COUNT:-2}
WORKER_DISK_CACHE_BYTES=${DATAVINE_GRAND_WORKER_DISK_CACHE_BYTES:-67108864}
WORKER_DISK_CACHE_ITEMS=${DATAVINE_GRAND_WORKER_DISK_CACHE_ITEMS:-2048}
WORKER_DISK_CACHE_ADMISSION_BYTES=${DATAVINE_GRAND_WORKER_DISK_CACHE_ADMISSION_BYTES:-67108864}
WORKER_DISK_CACHE_ADMISSION_ITEMS=${DATAVINE_GRAND_WORKER_DISK_CACHE_ADMISSION_ITEMS:-512}
FAILURE_ARGS=()
if [[ "${DATAVINE_GRAND_WORKER_LOSS:-0}" == "1" ]]; then
  FAILURE_ARGS+=(--worker-loss)
fi
MODE=${DATAVINE_GRAND_MODE:-full}
if [[ "${DATAVINE_GRAND_PROCESS_RUNNER:-0}" == "1" ]]; then
  FAILURE_ARGS+=(--process-runner)
fi
cd "$ROOT/taskvine/test"
exec python "$ROOT/acceptance/scripts/datavine_grand_challenge.py" \
  --tasks "$TASKS" --workers "$WORKERS" --worker-cores "$WORKER_CORES" \
  --mode "$MODE" --medium-bytes "$MEDIUM_BYTES" \
  --worker-loss-count "$WORKER_LOSS_COUNT" \
  --worker-disk-cache-bytes "$WORKER_DISK_CACHE_BYTES" \
  --worker-disk-cache-items "$WORKER_DISK_CACHE_ITEMS" \
  --worker-disk-cache-admission-bytes "$WORKER_DISK_CACHE_ADMISSION_BYTES" \
  --worker-disk-cache-admission-items "$WORKER_DISK_CACHE_ADMISSION_ITEMS" \
  --workflow-timeout "$WORKFLOW_TIMEOUT" \
  --large-bytes "$LARGE_BYTES" --json "${FAILURE_ARGS[@]}"
