#ifndef VINE_DATAVINE_PROTOCOL_H
#define VINE_DATAVINE_PROTOCOL_H

#include <stdint.h>

#define VINE_DATAVINE_RPC_MAGIC UINT32_C(0x44564331)
#define VINE_DATAVINE_RPC_VERSION 1
#define VINE_DATAVINE_RPC_REQUEST_HEADER 20
#define VINE_DATAVINE_RPC_RESPONSE_HEADER 24
#define VINE_DATAVINE_RPC_MAX_PAYLOAD (64U * 1024U * 1024U)

enum vine_datavine_rpc_opcode {
	VINE_DATAVINE_RPC_AUTH = 1,
	VINE_DATAVINE_RPC_PING = 2,
	VINE_DATAVINE_RPC_ALLOCATE_BATCH = 3,
	VINE_DATAVINE_RPC_PUBLISH_BATCH = 4,
	VINE_DATAVINE_RPC_CLAIM_WORKER = 5,
	VINE_DATAVINE_RPC_PUBLISH_OUTPUTS = 6,
	VINE_DATAVINE_RPC_DISCONNECT_WORKER = 7,
	VINE_DATAVINE_RPC_REPORT_REPLICA = 8,
	VINE_DATAVINE_RPC_RESOLVE_SOURCE = 9,
	VINE_DATAVINE_RPC_RELEASE_SOURCE = 10,
	VINE_DATAVINE_RPC_REGISTER_EDATA = 11,
	VINE_DATAVINE_RPC_GET_EDATA = 12,
	VINE_DATAVINE_RPC_INVALIDATE_REPLICA = 13,
	VINE_DATAVINE_RPC_RESTORE_REPLICA = 14,
	VINE_DATAVINE_RPC_CONFIRM_REPLICA_PRUNED = 15,
	VINE_DATAVINE_RPC_MARK_EDATA_SHARED = 16,
};

enum vine_datavine_rpc_status {
	VINE_DATAVINE_RPC_OK = 0,
	VINE_DATAVINE_RPC_INVALID = 1,
	VINE_DATAVINE_RPC_UNAUTHORIZED = 2,
	VINE_DATAVINE_RPC_REJECTED = 3,
	VINE_DATAVINE_RPC_INTERNAL = 4,
	VINE_DATAVINE_RPC_NOT_FOUND = 5,
};

#endif
